/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  getU8Encoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedInitializeStateInstruction,
  type ParsedUpdateStateInstruction,
} from '../instructions';

export const REPOSITORY_LAYOUT_PROGRAM_ADDRESS =
  'EuNENfWwZPyrHznUFNtqU3aBJoqyGJmrKeGXtXLWqkgb' as Address<'EuNENfWwZPyrHznUFNtqU3aBJoqyGJmrKeGXtXLWqkgb'>;

export enum RepositoryLayoutAccount {
  MyStateV1,
  MyStateV2,
}

export enum RepositoryLayoutInstruction {
  InitializeState,
  UpdateState,
}

export function identifyRepositoryLayoutInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): RepositoryLayoutInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (containsBytes(data, getU8Encoder().encode(0), 0)) {
    return RepositoryLayoutInstruction.InitializeState;
  }
  if (containsBytes(data, getU8Encoder().encode(1), 0)) {
    return RepositoryLayoutInstruction.UpdateState;
  }
  throw new Error(
    'The provided instruction could not be identified as a repositoryLayout instruction.'
  );
}

export type ParsedRepositoryLayoutInstruction<
  TProgram extends string = 'EuNENfWwZPyrHznUFNtqU3aBJoqyGJmrKeGXtXLWqkgb',
> =
  | ({
      instructionType: RepositoryLayoutInstruction.InitializeState;
    } & ParsedInitializeStateInstruction<TProgram>)
  | ({
      instructionType: RepositoryLayoutInstruction.UpdateState;
    } & ParsedUpdateStateInstruction<TProgram>);
