/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type InitializeMyStateV1IxData = { owner: Address; data: Array<number> };

export type InitializeMyStateV1IxDataArgs = InitializeMyStateV1IxData;

export function getInitializeMyStateV1IxDataEncoder(): FixedSizeEncoder<InitializeMyStateV1IxDataArgs> {
  return getStructEncoder([
    ['owner', getAddressEncoder()],
    ['data', getArrayEncoder(getU8Encoder(), { size: 32 })],
  ]);
}

export function getInitializeMyStateV1IxDataDecoder(): FixedSizeDecoder<InitializeMyStateV1IxData> {
  return getStructDecoder([
    ['owner', getAddressDecoder()],
    ['data', getArrayDecoder(getU8Decoder(), { size: 32 })],
  ]);
}

export function getInitializeMyStateV1IxDataCodec(): FixedSizeCodec<
  InitializeMyStateV1IxDataArgs,
  InitializeMyStateV1IxData
> {
  return combineCodec(
    getInitializeMyStateV1IxDataEncoder(),
    getInitializeMyStateV1IxDataDecoder()
  );
}
