/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type InitializeMyStateV2IxData = { owner: Address; data: Array<number> };

export type InitializeMyStateV2IxDataArgs = InitializeMyStateV2IxData;

export function getInitializeMyStateV2IxDataEncoder(): FixedSizeEncoder<InitializeMyStateV2IxDataArgs> {
  return getStructEncoder([
    ['owner', getAddressEncoder()],
    ['data', getArrayEncoder(getU8Encoder(), { size: 32 })],
  ]);
}

export function getInitializeMyStateV2IxDataDecoder(): FixedSizeDecoder<InitializeMyStateV2IxData> {
  return getStructDecoder([
    ['owner', getAddressDecoder()],
    ['data', getArrayDecoder(getU8Decoder(), { size: 32 })],
  ]);
}

export function getInitializeMyStateV2IxDataCodec(): FixedSizeCodec<
  InitializeMyStateV2IxDataArgs,
  InitializeMyStateV2IxData
> {
  return combineCodec(
    getInitializeMyStateV2IxDataEncoder(),
    getInitializeMyStateV2IxDataDecoder()
  );
}
