/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
} from '@solana/kit';

export type MyStateV2 = {
  owner: Address;
  data: Array<number>;
  updateCount: number;
  state: number;
  isInitialized: number;
  bump: number;
  padding: number;
};

export type MyStateV2Args = MyStateV2;

export function getMyStateV2Encoder(): FixedSizeEncoder<MyStateV2Args> {
  return getStructEncoder([
    ['owner', getAddressEncoder()],
    ['data', getArrayEncoder(getU8Encoder(), { size: 32 })],
    ['updateCount', getU32Encoder()],
    ['state', getU8Encoder()],
    ['isInitialized', getU8Encoder()],
    ['bump', getU8Encoder()],
    ['padding', getU8Encoder()],
  ]);
}

export function getMyStateV2Decoder(): FixedSizeDecoder<MyStateV2> {
  return getStructDecoder([
    ['owner', getAddressDecoder()],
    ['data', getArrayDecoder(getU8Decoder(), { size: 32 })],
    ['updateCount', getU32Decoder()],
    ['state', getU8Decoder()],
    ['isInitialized', getU8Decoder()],
    ['bump', getU8Decoder()],
    ['padding', getU8Decoder()],
  ]);
}

export function getMyStateV2Codec(): FixedSizeCodec<MyStateV2Args, MyStateV2> {
  return combineCodec(getMyStateV2Encoder(), getMyStateV2Decoder());
}

export function decodeMyStateV2<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<MyStateV2, TAddress>;
export function decodeMyStateV2<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<MyStateV2, TAddress>;
export function decodeMyStateV2<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<MyStateV2, TAddress> | MaybeAccount<MyStateV2, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getMyStateV2Decoder()
  );
}

export async function fetchMyStateV2<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<MyStateV2, TAddress>> {
  const maybeAccount = await fetchMaybeMyStateV2(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeMyStateV2<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<MyStateV2, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeMyStateV2(maybeAccount);
}

export async function fetchAllMyStateV2(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<MyStateV2>[]> {
  const maybeAccounts = await fetchAllMaybeMyStateV2(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeMyStateV2(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<MyStateV2>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeMyStateV2(maybeAccount));
}
