/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
} from '@solana/kit';
import {
  getStateDecoder,
  getStateEncoder,
  type State,
  type StateArgs,
} from '../types';

export type MyStateV1 = {
  isInitialized: number;
  owner: Address;
  state: State;
  data: Array<number>;
  updateCount: number;
  bump: number;
};

export type MyStateV1Args = {
  isInitialized: number;
  owner: Address;
  state: StateArgs;
  data: Array<number>;
  updateCount: number;
  bump: number;
};

export function getMyStateV1Encoder(): FixedSizeEncoder<MyStateV1Args> {
  return getStructEncoder([
    ['isInitialized', getU8Encoder()],
    ['owner', getAddressEncoder()],
    ['state', getStateEncoder()],
    ['data', getArrayEncoder(getU8Encoder(), { size: 32 })],
    ['updateCount', getU32Encoder()],
    ['bump', getU8Encoder()],
  ]);
}

export function getMyStateV1Decoder(): FixedSizeDecoder<MyStateV1> {
  return getStructDecoder([
    ['isInitialized', getU8Decoder()],
    ['owner', getAddressDecoder()],
    ['state', getStateDecoder()],
    ['data', getArrayDecoder(getU8Decoder(), { size: 32 })],
    ['updateCount', getU32Decoder()],
    ['bump', getU8Decoder()],
  ]);
}

export function getMyStateV1Codec(): FixedSizeCodec<MyStateV1Args, MyStateV1> {
  return combineCodec(getMyStateV1Encoder(), getMyStateV1Decoder());
}

export function decodeMyStateV1<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<MyStateV1, TAddress>;
export function decodeMyStateV1<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<MyStateV1, TAddress>;
export function decodeMyStateV1<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<MyStateV1, TAddress> | MaybeAccount<MyStateV1, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getMyStateV1Decoder()
  );
}

export async function fetchMyStateV1<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<MyStateV1, TAddress>> {
  const maybeAccount = await fetchMaybeMyStateV1(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeMyStateV1<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<MyStateV1, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeMyStateV1(maybeAccount);
}

export async function fetchAllMyStateV1(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<MyStateV1>[]> {
  const maybeAccounts = await fetchAllMaybeMyStateV1(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeMyStateV1(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<MyStateV1>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeMyStateV1(maybeAccount));
}
